---
kind: pipeline
name: default

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx:20.11@sha256:327b6fb15dc841cf80c7c429f60d695efd7c7a476fe363afac25a58befd4c203
    settings:
      auto_tag: true
      repo: mazzolino/shepherd
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    exclude:
      - pull_request
---
kind: signature
hmac: 7a382995e75bae16394a9cd0fbb34ed56ac392fa932b15ea57bda513240ee5f7

...
